#!/bin/bash
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=1
#SBATCH --account=design-lab
#SBATCH --time=72:00:00
#SBATCH --job-name=autorelax-TpPa1
#SBATCH --output=autorelax-TpPa1.out
#SBATCH --mem=2G
#SBATCH --mail-type=END,FAIL

cd $SLURM_SUBMIT_DIR

auto-relax.sh relax.in
Submitted batch job 3920773
